name: build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
          version: 1.4.309.0
          cache: true

      - name: Configure (Release)
        shell: pwsh
        run: |
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -DNOVA_FETCH_DEPS=ON

      - name: Build (Release, verbose)
        shell: pwsh
        run: |
          cmake --build build --config Release -- /m /v:minimal

      # Always upload logs + whatever built so we can inspect
      - name: Upload build logs and outputs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-and-out
          path: |
            build/**/*.log
            build/**/*.txt
            build/bin/Release/**
