name: build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
          version: 1.4.309.0
          cache: true

      - name: Configure (Release)
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release

      - name: Build (Release)
        run: cmake --build build --config Release -- /m

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: NovaEditor-Windows-Release
          path: build/bin/Release/
